Spiral framework integration
schranz-templating/templating pull request #56
Opened 2022-11-13 08:20 UTC by butschster

2022-11-13 13:23 UTC, butschster commented
You don't need to merge the PR, it's just an example

2022-11-13 13:33 UTC, alexander-schranz requested changes
@butschster really thank you for this valuable feedback. Its really nice to see that somebody of the frameworks is reviewing this integrations.

I added some small comments, let me know if you have time to fix them, else I can take tackle them when I will integrate your feedback then also for the other Template Engine Integrations.

PS: For testing there exist also a whole spiral project inside `examples/usages/spiral` which allow to start a spiral project where all engines are integrated in seperate routes.

2022-11-13 13:33 UTC, alexander-schranz commented on src/Integration/Spiral/Blade/Bootloader/BladeBootloader.php
> +        );
The integration will always provide the specific Renderer as a service. But also bind the Interface to that service.

```suggestion
        $binder->bindSingleton(
            BladeRenderer::class,
            static function (FactoryContract $factory): TemplateRendererInterface {
                return new BladeRenderer($factory);
            }
        );

        $binder->bind(TemplateRendererInterface::class, BladeRenderer::class);
```

This way we make sure somebody can inject and use the specific renderer, but a library/module can access the project defined renderer via TemplateRendererInterface.

2022-11-13 13:33 UTC, alexander-schranz commented on src/Integration/Spiral/SpiralView/Bootloader/SpiralViewBootloader.php
> -        $container->bind(TemplateRendererInterface::class, 'schranz_templating.renderer.spiral_view');
Like above the Interface should always be available in the container.

```suggestion
        $container->bind(TemplateRendererInterface::class, SpiralViewRenderer::class);
```

2022-11-13 13:33 UTC, alexander-schranz commented on src/Integration/Spiral/Twig/Bootloader/TwigBootloader.php
> -        $container->bind(TemplateRendererInterface::class, 'schranz_templating.renderer.twig');
```suggestion
        $container->bindSingleton(TwigRenderer::class, function (Environment $environment) {
            return new TwigRenderer($environment);
        });

        $container->bind(TemplateRendererInterface::class, 'schranz_templating.renderer.twig');
```

2022-11-13 13:33 UTC, alexander-schranz commented on src/Integration/Spiral/Twig/composer.json
> +        "spiral/core": "^3.0"
Looks like I forget them in this implementation, depending on the use imports I think we need:

```suggestion
        "spiral/boot": "^3.0",
        "spiral/config": "^3.0",
        "spiral/core": "^3.0"
```

2022-11-13 13:48 UTC, alexander-schranz commented
@butschster 

> First of all, I don't understand the reason of using string nameslike 'schranz_templating.renderer.smarty' for container aliases.

I'm coming from a Symfony background where this is [best practice for modules](https://symfony.com/doc/current/bundles/best_practices.html#services). The background there is that usage of a specific name avoids that a project accidentally overwrites a modules/bundle service, and defines more Interface more defines the public API.

But if you say that is not common in spiral I will definitely go the Spiral way here and avoid naming the services specific to the module.

> When you bind closures into container you can request dependencies as function arguments. You don't need request container and then get dependencies from them.

> Spiral framework Bootloader can automatically load depended bootloaders before loading current.

Thats are two really nice feature 👍

2022-11-14 19:54 UTC, alexander-schranz commented on src/Integration/Spiral/Twig/Bootloader/TwigBootloader.php
> -        $container->bind(TemplateRendererInterface::class, 'schranz_templating.renderer.twig');
I see this is handled over the SINGLETONS variable.

2022-11-14 19:55 UTC, alexander-schranz commented on src/Integration/Spiral/Twig/Bootloader/TwigBootloader.php
> +                $twigEngine = $container->get(TwigEngine::class);
Getting the Engine from the Container sadly ends in following exception:

> [Spiral\Views\Exception\EngineException] No associated environment found. in /Users/alexanderschranz/Documents/Projects/templating/examples/usages/spiral/vendor/spiral/twig-bridge/src/TwigEngine.php:74 

That is why I did go over the `ViewManager` which is setting correctly all things and throws no error.

2022-11-14 20:01 UTC, merged

2022-11-14 20:04 UTC, alexander-schranz commented
I could not push in your branch so I continued the changes here: https://github.com/schranz-templating/templating/pull/59

Thank you for this PR!

2022-11-15 08:53 UTC, butschster commented on src/Integration/Spiral/Twig/Bootloader/TwigBootloader.php
> +                $twigEngine = $container->get(TwigEngine::class);
Got it